//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDemo123
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {

        private static Entities1 _context;
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        public static Entities1 GetContext()
        {
            if (_context == null)
                _context = new Entities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<apartment_demands> apartment_demands { get; set; }
        public virtual DbSet<apartments> apartments { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<deals> deals { get; set; }
        public virtual DbSet<house_demands> house_demands { get; set; }
        public virtual DbSet<houses> houses { get; set; }
        public virtual DbSet<land_demands> land_demands { get; set; }
        public virtual DbSet<lands> lands { get; set; }
        public virtual DbSet<supplies> supplies { get; set; }
        public virtual DbSet<districts> districts { get; set; }

    }
}
