//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDemo123
{
    using System;
    using System.Collections.Generic;
    
    public partial class houses
    {
        public byte Id { get; set; }
        public string Address_City { get; set; }
        public string Address_Street { get; set; }
        public Nullable<int> Address_House { get; set; }
        public Nullable<int> Address_Number { get; set; }
        public double Coordinate_latitude { get; set; }
        public double Coordinate_longitude { get; set; }
        public int TotalFloors { get; set; }
        public double TotalArea { get; set; }
    }
}
